baseurl: 
baseTitle: Smart YouTube TV
sdkurl: https://developer.android.com/reference
excerpt_separator: <!--more-->
themename: 'theme-my'
title: Smart YouTube TV
description: Comfortable YouTube client for Android TV boxes
url: https://yuliskov.github.io
author: Yurii Lyskov
logo: /images/site_logo.png
email: firsthash@gmail.com
exclude:
  - old
lang:
  - en
  - ru
binaries:
  origin: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.9/SmartYouTubeTV_v6.8.9.apk
  beta: https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/Smart.YouTube.TV.Beta.6.8.2.apk
  MiTV2: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.6/SmartYouTubeTV_autoapk_s_2.apk
  Mystery: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.6/smartyoutubetv-betaFlavor-debug-Mystery.apk
bottom-links:
  -
    url: https://github.com/yuliskov/SmartYouTubeTV/releases/
    title: Old Releases
  -
    url: https://github.com/yuliskov/SmartYouTubeTV
    title: Source Code
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
