baseurl: /SmartYouTubeTV
baseTitle: Smart YouTube TV
sdkurl: https://developer.android.com/reference
excerpt_separator: <!--more-->
themename: 'theme-my'
title: Smart YouTube TV
description: Comfortable YouTube client for Android TV boxes
url: https://yuliskov.github.io
author: Yurii Lyskov
logo: /images/site_logo.png
exclude:
  - old
lang:
  - en
  - ru
binaries:
  origin: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.6/smartyoutubetv-originalFlavor-release.apk
  beta: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.6/smartyoutubetv-betaFlavor-release.apk
  MiTV2: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.6/SmartYouTubeTV_autoapk_s_2.apk
  Mystery: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.6/smartyoutubetv-betaFlavor-debug-Mystery.apk
bottom-links:
  -
    url: https://github.com/yuliskov/SmartYouTubeTV/releases/
    title: Downloads
  -
    url: https://github.com/yuliskov/SmartYouTubeTV
    title: Source Code
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
