baseurl: 
scripts: /scripts
baseTitle: Smart YouTube TV
sdkurl: https://developer.android.com/reference
excerpt_separator: <!--more-->
themename: 'style-custom'
title: Smart YouTube TV
description: Comfortable YouTube client for Android TV boxes
url: https://yuliskov.github.io
author: Yurii Lyskov
logo: /images/site_logo.png
email: firsthash@gmail.com
donation_paypal: https://www.donationalerts.com/r/firsthash
donation_privatbank: https://privatbank.ua/ru/sendmoney?payment=5fcdddf53e3d491d63fcb050e6e2e05f2f2678c2
exclude:
  - old
  - '*.bak'
  - '*.new'
lang:
  - en
  - ru
binaries:
  unified: https://github.com/yuliskov/SmartYouTubeTV/releases/download/stable/smartyoutubetv_latest.apk
  unified_test: https://github.com/yuliskov/SmartYouTubeTV/releases/
  kids: https://drive.google.com/uc?id=10Ba2k3enGyD9MK3UDiPRF5W_qp8oL0Uk
  MiTV2: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.6/SmartYouTubeTV_autoapk_s_2.apk
  Mystery: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.8.6/smartyoutubetv-betaFlavor-debug-Mystery.apk
  Live: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.14.18/SmartYouTubeTV_Vlive_v6.14.18_r.apk
xwalk_libs:
  https://drive.google.com/open?id=1_HM4DDAbCchAkCcAruWnJ4cGYDfXLEw9
bottom-links:
  -
    url: https://github.com/yuliskov/SmartYouTubeTV/releases/
    title: All Releases
    title_en: All Releases
    title_ru: Все релизы
  -
    url: https://github.com/yuliskov/SmartYouTubeTV
    title: Source Code
    title_en: Source Code
    title_ru: Исходный код
gems:
  - jekyll-seo-tag
  - jekyll-sitemap